version: "3.3"

services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
    labels:
      # HTTP to HTTPS redirection
      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # global redirect to https
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
      # Docker labels for enabling Traefik dashboard
      - "traefik.http.routers.traefik.rule=Host(`${MONITOR_DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=secure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
    environment:
      - "OVH_ENDPOINT=${OVH_ENDPOINT}"
      - "OVH_APPLICATION_KEY=${OVH_APPLICATION_KEY}"
      - "OVH_APPLICATION_SECRET=${OVH_APPLICATION_SECRET}"
      - "OVH_CONSUMER_KEY=${OVH_CONSUMER_KEY}"
    volumes:
      - "./traefik.toml:/traefik.toml"
      - "./letsencrypt:/letsencrypt/"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  default:
    external:
      name: "web"