version: "3.3"

services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.frontend.rule=Host:${MONITOR_DOMAIN}"
      - "traefik.port=8080"
    environment:
      - "OVH_ENDPOINT=${OVH_ENDPOINT}"
      - "OVH_APPLICATION_KEY=${OVH_APPLICATION_KEY}"
      - "OVH_APPLICATION_SECRET=${OVH_APPLICATION_SECRET}"
      - "OVH_CONSUMER_KEY=${OVH_CONSUMER_KEY}"
    volumes:
      - "./traefik.toml:/traefik.toml"
      - "./acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web
networks:
  web:
    external: true