[log]
  level = "DEBUG"

[global]
  sendAnonymousUsage = false

[entryPoints]
  [entryPoints.insecure]
    address = ":80"
  [entryPoints.secure]
    address = ":443"

[api]
  dashboard = true
  debug = false
  insecure = true

[providers]
  [providers.docker]
    endpoint ="unix:///var/run/docker.sock"
    watch = true
    exposedByDefault = true
    swarmMode = false
    network="web"

[certificatesResolvers.letsencrypt.acme]
  email = "damienmeur@gmail.com"
  storage = "acme.json"
  caserver = "https://acme-staging-v02.api.letsencrypt.org/directory"
  [dnsChallenge]
    provider= "ovh"
    delayBeforeCheck= 10
