version: '3'
services:
  express_static_production:
    build:
      context: ../../../
      dockerfile: ./backend/express_static/production/production.Dockerfile
    labels:
      - "traefik.http.routers.production_frontend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.production_frontend.entrypoints=secure"
      - "traefik.http.routers.production_frontend.tls.certresolver=letsencrypt"
networks:
  default:
    external:
      name: "web"