version: '3'

services:
  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.port=80"
      - "traefik.backend=${TRAEFIK_BACKEND}"
      - "traefik.frontend.rule=Host:${DOMAIN}"
      - "traefik.docker.network=web"

networks:
  web:
    external: true