version: '3'
services:
  express_static_staging:
    build:
      context: ../../../
      dockerfile: ./backend/express_static/staging/staging.Dockerfile
    labels:
      - "traefik.http.routers.staging_frontend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.staging_frontend.entrypoints=secure"
      - "traefik.http.routers.staging_frontend.tls.certresolver=letsencrypt"
    networks:
      - web
networks:
  web:
    external: true