version: '3'

services:
  mariadb:
    container_name: ${CONTAINER_DB_NAME}
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    networks:
      - db_network
    labels:
      - "traefik.enable=false"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  adminer:
    image: adminer:4.6.3-standalone
    labels:
      - "traefik.http.routers.adminer.rule=Host(`${ADMINER_DOMAIN}`)"
      - "traefik.http.routers.adminer.entrypoints=secure"
      - "traefik.http.routers.adminer.tls.certresolver=letsencrypt"
    networks:
      - db_network
      - web
    depends_on:
      - mariadb

volumes:
  db:

networks:
  web:
    external: true
  db_network:
    external: true