version: '3'

services:
  wordpress:
    container_name: ${CONTAINER_WP_NAME}
    image: wordpress:latest
    restart: unless-stopped
    volumes:
      - "./wordpress-files:/var/www/html"
      - "./wp-content:/var/www/html/wp-content"
      - "./htaccess/.htaccess:/var/www/html/.htaccess"
      - "./custom-plugins/house-projects.php:/var/www/html/wp-content/plugins/house-projects.php"ls -
    labels:
      - "traefik.http.routers.${CONTAINER_WP_NAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${CONTAINER_WP_NAME}.entrypoints=secure"
      - "traefik.http.routers.${CONTAINER_WP_NAME}.tls.certresolver=letsencrypt"
    networks:
      - web
      - db_network
    environment:
      WORDPRESS_DB_HOST: ${CONTAINER_DB_NAME}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}

networks:
  web:
    external: true
  db_network:
    external: true