version: '3'

services:
  wordpress:
    container_name: ${CONTAINER_WP_NAME}
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - "./wp-permission-init.sh:/usr/local/bin/apache2-custom.sh"
    labels:
      - "traefik.http.routers.${CONTAINER_WP_NAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${CONTAINER_WP_NAME}.entrypoints=secure"
      - "traefik.http.routers.${CONTAINER_WP_NAME}.tls.certresolver=letsencrypt"
    networks:
      - web
      - db_network
    environment:
      WORDPRESS_DB_HOST: ${CONTAINER_DB_NAME}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}

networks:
  web:
    external: true
  db_network:
    external: true